### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by BenoitDuffez** [marian-m12l/studio#138]
My kid loves their story teller and I love open source and open devices.
She is subscribed to 'Les belles histoires' and we get a CD every month. I save them as mp3 for my streaming server (in the car...) and also I have created a library for the story teller.

I love it and I know what it's like to build open source and I am grateful.
I tried to find your email on GitHub or on your commit messages but it's hidden.

Where can I donate? I'm sure you drink coffee or beer and I'd love to pay you a round.

**Comment by marian-m12l** [comment]
Thanks for the feedback, that's great to hear! I really appreciate the gesture, but tbh I started this project first and foremost for my kids and (let's be honest...) myself, and I'm just thrilled that it can be useful to others :-) Let's hope that the new firmware can be supported at some point so the project stays relevant!

**Comment by diegantobass** [comment]
Hey @marian-m12l, if you ever change your mind about allowing us to pay you a round of anything, beer, coffee, tea or java juice ([yes, java juice](https://www.javajuice.com.au/)), let us know. Especially now that the project seems to be in a tougher situation due to the firmware upgrade and coming new versions. Thanks for the great work!

**Comment by gregtap** [comment]
Yes let us know and count me in.
