### ISSUE TITLE
Dealing with audio

### ISSUE THREAD

**Issue by xounamoun** [marian-m12l/studio#192]
Well, this is not specifically linked with STUdio since everything's working. But I've been trying for a long time now to normalize the audio files that I plug in, so as they have the same volume as the Lunii official stories. For some reason that I don't understand, even if I amplify them, the sound is always below the other tracks. 

Is there any suggested path for recording + normalizing written somewhere for a user on Linux (Ubuntu) ? I've seen a couple of solutions (mp3gain, or sox --norm) but this does not seem to be enough. Maybe I just miss the good parameter to fill in, but I would be glad if anyone encountering the same issue has an idea. 

I hope this issue is too much off-topic.

**Comment by marian-m12l** [comment]
@xounamoun I am not a sound engineer, so I won't be of much help. In my opinion this is mostly a manual task, because the processing varies depending on what the file contains (short/long, loud/calm, ...). Personally I try to record at consistent levels, then normalize with a high peak amplitude (-3.0dB IIRC). If necessary, I can adjust the volume of a section relative to the rest. However it generally sounds lower that the official stories. I think the keyword here is "loudness", which is what mp3gain and the likes are made for, but I don't know much about it.

**Comment by xounamoun** [comment]
@marian-m12l Thanks for the answer. I eventually manage to get clean audio with the same level of " loudness " as the Lunii. The solution was simple : buy a proper microphone and stop using the cheap one of my smartphone or the (even cheaper) one of my laptop. It cost me only 30€ and simplifies *a lot* the whole recording process. I really thank so much for this amazing work you have done, Marian !

**Comment by marian-m12l** [comment]
@xounamoun Indeed a good microphone goes a long way!
