### ISSUE TITLE
A repository to share homemade stories

### ISSUE THREAD

**Issue by jqueguiner** [marian-m12l/studio#89]
Hi, what do you think about having a place to share our .zip packed stories ?

**Comment by dasebasto** [comment]
Yes, we definitely need that!

We could publish homemade story packs, as well as free public podcasts rebundled as packs (it's a gray area in terms of copyright law here, but as long as we stick to audio content available for free and don't monetize it, it could be considered fair use).

For instance, I have created a pack of about 20 of these great stories (in French): https://www.franceinter.fr/emissions/les-odyssees

It took me at least 2 hours to record the stories titles, organize the pictures, set the pack structure etc.

I'd be happy to share the result so that everyone does not have to make the same work again.

**Comment by T1nd4** [comment]
Hi dasebasto ! Can you give us a link of your pack plz ?

________________________________
De : dasebasto <notifications@github.com>
Envoyé : Sunday, May 3, 2020 3:50:18 PM
À : marian-m12l/studio <studio@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [marian-m12l/studio] A repository to share homemade stories (#89)


Yes, we definitely need that!

We could publish homemade story packs, as well as free public podcasts rebundled as packs (it's a gray area in terms of copyright law here, but as long as we stick to audio content available for free and don't monetize it, it could be considered fair use).

For instance, I have created a pack of about 20 of these great stories (in French): https://www.franceinter.fr/emissions/les-odyssees

It took me at least 2 hours to record the stories titles, organize the pictures, set the pack structure etc.

I'd be happy to share the result so that everyone does not have to make the same work again.

**Comment by jqueguiner** [comment]
I have a personal Nextcloud that we could use with public file sharing.

**Comment by jqueguiner** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/690878/80941419-af378c80-8de2-11ea-9710-93bddc412056.png">

**Comment by ftiers** [comment]
I've create a history pack with the free "lunii+" history. (in french)
Where can i share it ?

**Comment by ftiers** [comment]
> I have a personal Nextcloud that we could use with public file sharing.

Please share your Cloud ?

**Comment by T1nd4** [comment]
You can use dl.freefr to share your content for the coming month. Hope we will find a better solution.

________________________________
De : BBK <notifications@github.com>
Envoyé : Tuesday, May 5, 2020 9:35:24 AM
À : marian-m12l/studio <studio@noreply.github.com>
Cc : T1nd4 <lebeneur@hotmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [marian-m12l/studio] A repository to share homemade stories (#89)


I have a personal Nextcloud that we could use with public file sharing.

Please share your Cloud ?

**Comment by DavidZurmely** [comment]
Hi everybody ! Is there such a place ? 
@dasebasto I'm very interested in your pack !
I created 2 games in french : one to learn bird songs (11 birds to listen and identify) and one to learn animal footprints (12 animals). For each song/footprint, you have 3 choices. 
I would be happy to share this with you !

**Comment by itdaboyz** [comment]
> Hi everybody ! Is there such a place ?
> @dasebasto I'm very interested in your pack !
> I created 2 games in french : one to learn bird songs (11 birds to listen and identify) and one to learn animal footprints (12 animals). For each song/footprint, you have 3 choices.
> I would be happy to share this with you !

That seems great!

**Comment by jqueguiner** [comment]
Hi for upload use :  https://muage.org/owncloud/s/C2CY5q5F6fAZtQ6
and for download : https://muage.org/owncloud/s/rRa2potrXQBYP3i

**Comment by jqueguiner** [comment]
I'll find something better in the futur but works great for now

**Comment by marian-m12l** [comment]
Hi all,

Thanks for the feedback and for being so enthusiastic and passionate about these stories! :-)

Believe me, I do understand the urge to share the work that went into carefully crafting such stories. The idea of creating a platform to share homemade stories did cross my mind more than once.

But here's the catch: I don't think that people would create that much content **that could be shared**. From what I can tell, people create mostly two kinds of story packs:
* Packaging existing recordings, either available freely on the Internet or from CDs they own, to be played on the Lunii,
* Homemade recordings for or with their kids (either an original story or from an existing piece of work).

Both usages are fine by me (although I really recommend creating and recording stories with kids!), but do not qualify as stories that you **can** or **want** to share.

So what else would be shared on such a platform then? To me, it feels that there are three kinds left:
* Actual homemade stories, with an original plot, homemade recordings (voices and potentially musics/songs), and homemade graphics,
* Homemade stories, but with some protected content (plot, recordings, musics/songs or graphics),
* Or, of course, plain piracy, **which I cannot condone**.

Being able to easily share story packs of that first kind would be really awesome! But truthfully, what a rare beast qualifying story packs must be! All in all, it feels like having such a sharing platform would cause more headaches than good...

All this to explain why, unless you are creating your **own** stories, **for which you fully own all legal rights**, I cannot encourage sharing story packs, and **I'm asking you to _not_ post links to unqualifying stories**.

Hope you still enjoy the application! :-)

**Comment by Juke34** [comment]
Why not sharing homemade content by torrent, e.g. https://www.yggtorrent.se?
@DavidZurmely I'm really interested by your work, could you share it with me?

**Comment by dasebasto** [comment]
A small community of French users is starting there: https://www.dealabs.com/discussions/discussion-utilisation-de-studio-pour-lunii-1876791

There is already a list of downloadable packs created by users (no piracy).

To keep this repo "clean", I suggest all discussions regarding sharing/publishing packs take place there.
